### ISSUE TITLE
window is not defined when running from electron main thread

### ISSUE THREAD

**Issue by Petah** [superRaytin/image-clipper#1]
```

Unhandled rejection ReferenceError: window is not defined
    at ImageClipper.__createImage (/home/petah/my-project/node_modules/image-clipper/lib/clipper.js:449:13)
    at ImageClipper.loadImageFromUrl (/home/petah/my-project/node_modules/image-clipper/lib/clipper.js:83:20)
    at ImageClipper.image (/home/petah/my-project/node_modules/image-clipper/lib/clipper.js:120:10)
    at imageClipper (/home/petah/my-project/node_modules/image-clipper/lib/index.js:36:15)
    at Promise (/home/petah/my-project/app/models/asset.js:29:13)
    at Promise._execute (/home/petah/my-project/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/petah/my-project/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/home/petah/my-project/node_modules/bluebird/js/release/promise.js:77:14)
    at Asset.generateThumbnail (/home/petah/my-project/app/models/asset.js:28:16)
    at Asset.findById.then (/home/petah/my-project/test-model.js:9:11)
    at tryCatcher (/home/petah/my-project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/petah/my-project/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/petah/my-project/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/petah/my-project/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/petah/my-project/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/petah/my-project/node_modules/bluebird/js/release/async.js:138:16)
```

**Comment by superRaytin** [comment]
Ah, maybe you should try it in [browserWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md).
